Start working on our own version of `cfg(target_has_atomic)`
mystor/radium pull request #4
Opened 2020-09-15 02:26 UTC by myrrlyn

I've been unhappy with our vague guessing of what atomics are available, and the #3 issue shows a target completely outside the scope of our temporary patch.

This branch uses a build script to inspect the `TARGET` environment variable, which Cargo helpfully sets to the value of the `--target ARCH` flag. This will be one of the targets enumerated in `rustup target list`.

I am running this commit through the `bitvec` cross-compile suite. Given that this suite is *extremely slow*, I expect that I will update with new targets as I discover their failures.

In the meantime, I would like review on whether we think this is an appropriate solution to the problem, and how we can make the script easily accessible to users to update with their architectures as needed.

2020-09-15 03:28 UTC, myrrlyn commented
My `just cross` task has completed successfully with these commits. I don't feel like searching out the rest of the targets.

2020-09-16 14:17 UTC, myrrlyn commented
This is driving me insane. I think I may actually bite the bullet and implement `available()` in the compiler just so I can throw all of this work away.

2020-09-16 18:01 UTC, mystor requested changes
If we're going to need the build script anyway, as the information isn't available from the `target_arch` config variable, let's just do it all in the build script. No reason to have the information split across two sources.

Sorry about asking for you to switch to using macros. I didn't realize that it wasn't possible to implement without a build script >_>

2020-09-18 22:25 UTC, mystor approved these changes

2020-09-18 22:25 UTC, mystor commented on build.rs
> +//! existing `cfg` infrastructure, it belongs in the macro.
The macro doesn't exist anymore, so let's drop it from the comment.

2020-09-18 22:25 UTC, mystor commented on build.rs
> +        // here, rather than in the macro.
The macro doesn't exist anymore :-)

2020-09-18 22:25 UTC, mystor commented on src/lib.rs
> +		}
Please fix the indentation of these lines.

2020-09-18 22:25 UTC, mystor commented on src/lib.rs
> +    }
We could also do this with the types from `types::RadiumT` :-)

2020-09-18 22:43 UTC, myrrlyn commented on build.rs
> +//! existing `cfg` infrastructure, it belongs in the macro.
lol I love to "update documentation"

2020-09-18 22:46 UTC, myrrlyn commented on src/lib.rs
> +		}
This is what I get for not leaving `cargo watch -x fmt` running while I work, thanks VSC

2020-09-18 23:21 UTC, merged